#!/bin/bash
cd $HOME/Downloads
ARCH=$(uname -m | cut -d_ -f2)
if [ $ARCH == 64 ]; then
  IRON=iron64
else
  IRON=iron
fi
INSTALLED=$(dpkg -l | grep "^ii  iron" 2> /dev/null)
if test $1; then
  if [[ "$1" == "up" || "$1" == "upgrade" ]]; then
    INSTALLED=""
  else
    echo "Invalid option.  Usage: $0 [up|upgrade]"
    exit 1
  fi
fi
if [ -z "$INSTALLED" ]; then
  WGET=$(which wget 2> /dev/null)
  if [ $? == 1 ]; then
    sudo apt-get install wget
  fi
  if [ -f $IRON.deb ]; then
    rm -f $IRON.deb
  fi
  wget http://www.srware.net/downloads/$IRON.deb
  if [ ! -f $IRON.deb ]; then
    echo "Unable to locate $IRON.deb.  Install failed."
    exit 1
  fi
  sudo dpkg -i $IRON.deb
  if [ ! -f /usr/share/applications/iron.desktop ]; then
    echo "Unable to locate iron.desktop.  Install failed."
    exit 1
  fi
  rm -f $IRON.deb
fi
FLASH=$(dpkg -l | grep "^ii  adobe-flashplugin" 2> /dev/null)
if [ -z "$FLASH" ]; then
  sudo apt-get update
  SEARCH=$(apt-cache search adobe-flashplugin)
  if [ ! -z "$SEARCH" ]; then
    sudo apt-get install adobe-flashplugin
  fi
fi
LIB="/usr/lib/adobe-flashplugin/libpepflashplayer.so"
VER=$(strings $LIB 2> /dev/null | grep LNX | cut -d ' ' -f 2 | sed -e "s/,/./g")
if [ -z "$VER" ]; then
  FLASH=$(dpkg -l | grep "^ii  flashplugin-installer" 2> /dev/null)
  if [ -z "$FLASH" ]; then
    SEARCH=$(apt-cache search flashplugin-installer)
    if [ ! -z "$SEARCH" ]; then
      sudo apt-get install flashplugin-installer
    fi
  fi
  LIB="/usr/lib/flashplugin-installer/libflashplayer.so"
  VER=$(strings $LIB 2> /dev/null | grep LNX | cut -d ' ' -f 2 | sed -e "s/,/./g")
  if [ -z "$VER" ]; then
    FLASH=$(dpkg -l | grep "^ii  pepperflashplugin-nonfree" 2> /dev/null)
    if [ -z "$FLASH" ]; then
      SEARCH=$(apt-cache search pepperflashplugin-nonfree)
      if [ ! -z "$SEARCH" ]; then
        sudo apt-get install pepperflashplugin-nonfree
      fi
    fi
    LIB="/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so"
    VER=$(strings $LIB 2> /dev/null | grep LNX | cut -d ' ' -f 2 | sed -e "s/,/./g")
    if [ -z "$VER" ]; then
      echo "Unable to determine the Pepperflash version.  Install failed."
      exit 1
    fi
  fi
fi
IRONVER=$(dpkg -l | grep "^ii  iron" | xargs | cut -d' ' -f3 2> /dev/null)
if [ -z "$IRONVER" ]; then
  echo "SRWare Iron with Pepperflash not installed."
  exit 1
fi
PEPPERFLASH=$(grep pepperflash /usr/share/applications/iron.desktop 2> /dev/null)
if [ ! -z "$PEPPERFLASH" ]; then
  echo "SRWare Iron $IRONVER with Pepperflash $VER already installed."
else
  sudo sed -i "s|/usr/share/iron/iron|/usr/share/iron/iron --ppapi-flash-path=$LIB --ppapi-flash-version=$VER|" /usr/share/applications/iron.desktop
  echo "SRWare Iron $IRONVER with Pepperflash $VER installed successfully."
fi
